services:
  webapp:
    image: vayaros/grindsoft:latest
    ports:
      - "8081:8080"  
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    volumes:
      - ./data:/app/data
    networks:
      - app-network  

networks:
  app-network:
    driver: bridge 

volumes:
  sqlite-data:
    driver: local

