version: '3.8'  

services:
  webapp:
    image: vayaros/grindsoft:latest
    ports:
      - "8081:8080"  
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    networks:
      - app-network  

networks:
  app-network:
    driver: bridge 
